// <auto-generated />
using CartoLogger.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartoLogger.Persistence.Migrations
{
    [DbContext(typeof(CartoLoggerDbContext))]
    [Migration("20251102015153_ExplicitFavoriteMaps")]
    partial class ExplicitFavoriteMaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CartoLogger.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Geometry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("UserId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.UserFavoriteMap", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("UserFavoriteMaps");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.Feature", b =>
                {
                    b.HasOne("CartoLogger.Domain.Entities.Map", "Map")
                        .WithMany("Features")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CartoLogger.Domain.Entities.User", "User")
                        .WithMany("Features")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.Map", b =>
                {
                    b.HasOne("CartoLogger.Domain.Entities.User", "User")
                        .WithMany("Maps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CartoLogger.Domain.Entities.LatLng", "View", b1 =>
                        {
                            b1.Property<int>("MapId")
                                .HasColumnType("int");

                            b1.Property<double>("Lat")
                                .HasColumnType("double")
                                .HasColumnName("ViewLatitude");

                            b1.Property<double>("Lng")
                                .HasColumnType("double")
                                .HasColumnName("ViewCenterLongitude");

                            b1.HasKey("MapId");

                            b1.ToTable("Maps");

                            b1.WithOwner()
                                .HasForeignKey("MapId");
                        });

                    b.Navigation("User");

                    b.Navigation("View")
                        .IsRequired();
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.UserFavoriteMap", b =>
                {
                    b.HasOne("CartoLogger.Domain.Entities.Map", "Map")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartoLogger.Domain.Entities.User", "User")
                        .WithMany("FavoriteMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.Map", b =>
                {
                    b.Navigation("FavoritedBy");

                    b.Navigation("Features");
                });

            modelBuilder.Entity("CartoLogger.Domain.Entities.User", b =>
                {
                    b.Navigation("FavoriteMaps");

                    b.Navigation("Features");

                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
