// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ProgramacionOrientadaAObjetosContext))]
    [Migration("20251106030015_AddedRancherAndRelationshipToRanch")]
    partial class AddedRancherAndRelationshipToRanch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Domain.Livestock.Animal", b =>
                {
                    b.Property<Guid>("IdRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("CorralId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("IdBreed")
                        .HasColumnType("int");

                    b.Property<int>("IdRanch")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecie")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdRegistration");

                    b.HasIndex("CorralId");

                    b.HasIndex("IdBreed");

                    b.HasIndex("IdRanch");

                    b.HasIndex("IdSpecie");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.Domain.Locations.Corral", b =>
                {
                    b.Property<Guid>("IdCorral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCorral");

                    b.ToTable("Corrals");
                });

            modelBuilder.Entity("Core.Domain.Locations.Ranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RancherId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RancherId");

                    b.ToTable("Ranches", (string)null);
                });

            modelBuilder.Entity("Core.Domain.People.Rancher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Ranchers");
                });

            modelBuilder.Entity("Core.Domain.Taxonomy.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SpecieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecieId");

                    b.ToTable("Breeds", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Taxonomy.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ScientificName")
                        .IsUnique();

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Livestock.Goat", b =>
                {
                    b.HasBaseType("Core.Domain.Livestock.Animal");

                    b.Property<decimal>("MilkProductionPerDay")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("Goats");
                });

            modelBuilder.Entity("Core.Domain.Livestock.Horse", b =>
                {
                    b.HasBaseType("Core.Domain.Livestock.Animal");

                    b.Property<decimal>("MaxSpeed")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("Core.Domain.Livestock.Animal", b =>
                {
                    b.HasOne("Core.Domain.Locations.Corral", "Corral")
                        .WithMany("Animals")
                        .HasForeignKey("CorralId");

                    b.HasOne("Core.Domain.Taxonomy.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("IdBreed")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Locations.Ranch", "Ranch")
                        .WithMany("Animals")
                        .HasForeignKey("IdRanch")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Taxonomy.Specie", "Specie")
                        .WithMany("Animals")
                        .HasForeignKey("IdSpecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Corral");

                    b.Navigation("Ranch");

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Core.Domain.Locations.Ranch", b =>
                {
                    b.HasOne("Core.Domain.People.Rancher", "Rancher")
                        .WithMany("Ranches")
                        .HasForeignKey("RancherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rancher");
                });

            modelBuilder.Entity("Core.Domain.Taxonomy.Breed", b =>
                {
                    b.HasOne("Core.Domain.Taxonomy.Specie", "Specie")
                        .WithMany("Breeds")
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Core.Domain.Livestock.Goat", b =>
                {
                    b.HasOne("Core.Domain.Livestock.Animal", null)
                        .WithOne()
                        .HasForeignKey("Core.Domain.Livestock.Goat", "IdRegistration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Livestock.Horse", b =>
                {
                    b.HasOne("Core.Domain.Livestock.Animal", null)
                        .WithOne()
                        .HasForeignKey("Core.Domain.Livestock.Horse", "IdRegistration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Locations.Corral", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Core.Domain.Locations.Ranch", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Core.Domain.People.Rancher", b =>
                {
                    b.Navigation("Ranches");
                });

            modelBuilder.Entity("Core.Domain.Taxonomy.Specie", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Breeds");
                });
#pragma warning restore 612, 618
        }
    }
}
